"""Add reserved param to table

Revision ID: 1c0696c7c0f0
Revises: ae64d2c050d8
Create Date: 2025-04-27 18:30:13.802641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0696c7c0f0'
down_revision: Union[str, None] = 'ae64d2c050d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('reserved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'reserved')
    # ### end Alembic commands ###
