"""Add new params Restaurant

Revision ID: ae64d2c050d8
Revises: ec5f7c3b64e7
Create Date: 2025-04-27 15:55:17.633977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae64d2c050d8'
down_revision: Union[str, None] = 'ec5f7c3b64e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('description', sa.String(), nullable=False))
    op.add_column('restaurants', sa.Column('restaurant_type', sa.String(), nullable=False))
    op.add_column('restaurants', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'phone_number')
    op.drop_column('restaurants', 'restaurant_type')
    op.drop_column('restaurants', 'description')
    # ### end Alembic commands ###
