"""add number_of_people to booking table

Revision ID: d2d9a23357a5
Revises: 0071546db06a
Create Date: 2025-04-28 09:39:45.102699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d9a23357a5'
down_revision: Union[str, None] = '0071546db06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('number_of_people', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'number_of_people')
    # ### end Alembic commands ###
